### ISSUE TITLE
Random crashes at view loading time

### ISSUE THREAD

**Issue by dirtyhenry** [FlaneurApp/FlaneurImagePicker#4]
When the image picker is presented, we can get random crashes occurring at the following position in `emptyView(for:)`:

        if currentImageSource == nil // No current image source
            || section != .pickerView // The section is not the picker view
            || imageProvider.isAuthorized() // The image provider has already been authorized
        {
            return nil
        }

It seems that `imageProvider` (declared as a `FlaneurImageProvider!`) might be `nil` at this point.

**Comment by dirtyhenry** [comment]
`imageProvider` is set asynchronously in the background so if the asynchronous block takes too much time to run, the code will crash. It can be reproduced 100% of the time by adding a sleep instruction in the block. => Declaring `imageProvider` as `FlaneurImageProvider?` should fix this.

@25matt12 Any memories why you asked the `didSet` observer to run asynchronously in the background? (no worried if it's been too long and you don't remember anymore)

**Comment by 25matt12** [comment]
Sorry I really don't remember why I did it but it seems that you fixed it, nice job!
